[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

# Redirect khusus untuk endpoint API
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api/api"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Redirect ke halaman utama Netlify untuk UI aplikasi
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

# Redirect untuk route lainnya
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 