services:
  - type: web
    name: hospital-finance
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080 